from pathlib import Path

path = Path('ui/digirupee-app.js')
s = path.read_text(encoding='utf-8')
start = s.index('  function injectAuth() {')
end = s.index('  async function submitAuth(event) {', start)

block = r'''  function digiUsdtLogo(size = 34) {
    return `<svg viewBox="0 0 48 48" width="${size}" height="${size}" aria-hidden="true"><circle cx="24" cy="24" r="24" fill="#26A17B"/><path fill="#fff" d="M26.6 25.9v-.1c-.2 0-1 .1-2.6.1-1.3 0-2.2 0-2.5-.1v.1c-5 .2-8.7 1.1-8.7 2.2 0 1.1 3.7 2 8.7 2.2v7.8h5.1v-7.8c4.9-.2 8.6-1.1 8.6-2.2 0-1.1-3.7-2-8.6-2.2Zm0 3.5v-3c4 .2 7 .9 7 1.7 0 .8-3 1.5-7 1.7v-.4Zm-5.1.4c-4.1-.2-7.1-.9-7.1-1.7 0-.8 3-1.5 7.1-1.7v3.4ZM30.3 11H17.8v3.8h4.2v3.5h-4.2v3.8H30.3v-3.8h-4.1v-3.5h4.1V11Z"/></svg>`;
  }

  function injectAuth() {
    const style = document.createElement('style');
    style.textContent = `
      .digi-auth{--auth-bg:#07080b;--auth-panel:#111319;--auth-line:#252934;--auth-text:#f7f8fb;--auth-muted:#9ca3af;--auth-gold:#f4c84e;--auth-green:#26a17b;position:fixed;inset:0;z-index:1000;overflow:auto;padding:max(18px,env(safe-area-inset-top)) 16px max(20px,env(safe-area-inset-bottom));background:radial-gradient(circle at 80% 12%,rgba(38,161,123,.10),transparent 28%),radial-gradient(circle at 10% 55%,rgba(255,255,255,.035),transparent 32%),linear-gradient(180deg,#090a0e 0%,#07080b 100%);color:var(--auth-text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif}
      .digi-auth[hidden]{display:none}.digi-auth *{box-sizing:border-box}.digi-auth button,.digi-auth input{font:inherit}.digi-auth button{cursor:pointer}.digi-auth-shell{width:min(100%,430px);min-height:calc(100svh - 42px);margin:0 auto;display:flex;flex-direction:column}.digi-auth-topbar{display:flex;align-items:center;justify-content:space-between;gap:12px;position:relative;z-index:2}.digi-auth-brand{display:flex;align-items:center;gap:10px}.digi-auth-brand-mark{width:42px;height:42px;display:grid;place-items:center;filter:drop-shadow(0 10px 22px rgba(0,0,0,.32))}.digi-auth-brand strong{display:block;font-size:15px;letter-spacing:.01em}.digi-auth-brand small{display:block;color:#7f8794;font-size:10px;margin-top:2px}.digi-auth-secure{display:flex;align-items:center;gap:7px;color:#aab0ba;font-size:10px;padding:8px 10px;border:1px solid #252933;border-radius:999px;background:rgba(16,18,24,.78);backdrop-filter:blur(10px)}.digi-auth-secure-dot{width:7px;height:7px;border-radius:50%;background:#20c997;box-shadow:0 0 0 4px rgba(32,201,151,.08)}
      .digi-auth-stage{flex:1;display:flex;flex-direction:column;justify-content:center;padding-top:18px}.digi-auth-visual{min-height:170px;position:relative;display:flex;align-items:flex-end;padding:12px 4px 6px}.digi-auth-copy{max-width:295px}.digi-auth-eyebrow{display:inline-flex;align-items:center;gap:7px;color:#8fe1c6;font-size:10px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.digi-auth-eyebrow:before{content:'';width:18px;height:1px;background:#26a17b}.digi-auth-copy h1{margin:12px 0 9px;font-size:34px;line-height:1.02;letter-spacing:-.045em;max-width:315px;color:#fff}.digi-auth-copy p{margin:0;color:#9ca3af;font-size:12px;line-height:1.55;max-width:320px}.digi-auth-orb{position:absolute;right:5px;top:6px;width:112px;height:112px;border-radius:34px;transform:rotate(11deg);background:linear-gradient(145deg,#2ebd8f,#1b8f6c);box-shadow:0 20px 40px rgba(38,161,123,.22),inset 0 0 0 1px rgba(255,255,255,.28);display:grid;place-items:center}.digi-auth-orb svg{transform:rotate(-11deg);filter:drop-shadow(0 10px 18px rgba(0,0,0,.20))}.digi-auth-chip{position:absolute;border:1px solid rgba(255,255,255,.12);background:rgba(17,19,25,.90);backdrop-filter:blur(10px);color:#d8dbe2;border-radius:13px;padding:8px 10px;font-size:9px;box-shadow:0 10px 30px rgba(0,0,0,.25)}.digi-auth-chip.one{right:82px;top:102px}.digi-auth-chip.two{right:8px;top:132px}.digi-auth-chip b{color:#85dfc0;font-size:10px}
      .digi-auth-card{margin-top:10px;border:1px solid #262a34;border-radius:24px;background:linear-gradient(180deg,rgba(20,22,29,.98),rgba(13,15,20,.98));box-shadow:0 22px 70px rgba(0,0,0,.45);overflow:hidden}.digi-auth-form-wrap{padding:18px}.digi-auth-form-title{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}.digi-auth-form-title h2{margin:0;font-size:18px;letter-spacing:-.02em}.digi-auth-form-title p{margin:4px 0 0;color:#858d99;font-size:10px;line-height:1.45}.digi-auth-badge{padding:7px 9px;border-radius:999px;background:#1a1d24;color:#cfd3da;font-size:9px;border:1px solid #2a2f3a;white-space:nowrap}.digi-auth-fields{display:grid;gap:11px}.digi-auth-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.digi-auth-field{display:grid;gap:6px}.digi-auth-field label{color:#a9b0bb;font-size:10px;font-weight:700;letter-spacing:.02em}.digi-auth-input-shell{position:relative;display:flex;align-items:center;min-height:49px;border:1px solid #2a2f38;border-radius:13px;background:#0c0e13;transition:.18s ease}.digi-auth-input-shell:focus-within{border-color:#328d72;box-shadow:0 0 0 3px rgba(38,161,123,.08)}.digi-auth-icon{width:42px;display:grid;place-items:center;color:#656d79;font-size:14px;flex:none}.digi-auth-input-shell input{width:100%;height:47px;border:0;outline:0;background:transparent;color:#fff;padding:0 12px 0 0;font-size:13px}.digi-auth-input-shell input::placeholder{color:#5f6671}.digi-auth-password-btn{border:0;background:transparent;color:#8f97a3;padding:0 12px;font-size:10px}.digi-auth-meta{margin-top:9px;color:#777f8c;font-size:9px}.digi-auth .error{min-height:17px;color:#ff7784;font-size:10px;margin-top:8px}.digi-auth-primary{margin-top:3px;width:100%;min-height:50px;border:0;border-radius:14px;background:linear-gradient(100deg,#f1c94f,#ffd96c);color:#201800;font-weight:900;font-size:13px;box-shadow:0 12px 26px rgba(184,135,23,.18)}.digi-auth-primary:active{transform:translateY(1px)}.digi-auth-register-link{margin-top:15px;display:flex;align-items:center;justify-content:center;gap:6px;color:#7f8794;font-size:10px}.digi-auth-register-link button,.digi-auth-back{border:0;background:transparent;color:#f1cf67;font-weight:800;padding:2px 0;font-size:10px}.digi-auth-back{display:block;width:100%;margin-top:13px}.digi-auth-terms{color:#656d79;font-size:9px;line-height:1.45;text-align:center;margin:14px 10px 0}.digi-auth-terms b{color:#9ca3af}.digi-auth-foot{margin:15px 0 0;display:flex;justify-content:center;align-items:center;gap:6px;color:#6f7682;font-size:9px}.digi-auth-foot span{color:#2fb989}.digi-auth-challenge{padding:3px 0 0}
      .digi-security-extra{margin-top:12px;padding:11px;border:1px solid #292c34;border-radius:12px;background:#0c0e12}.digi-security-extra code{word-break:break-all;color:#f4d66e;font-size:10px}.digi-empty{padding:18px;text-align:center;color:#8d919b;font-size:11px}.digi-action-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.digi-action-row button{flex:1;min-width:120px}.digi-copy{word-break:break-all;color:#f4d66e;font-size:11px}
      @media(max-width:370px){.digi-auth-orb{width:92px;height:92px;border-radius:28px;right:2px}.digi-auth-orb svg{width:51px;height:51px}.digi-auth-copy h1{font-size:30px;max-width:260px}.digi-auth-row{grid-template-columns:1fr}.digi-auth-chip.two{display:none}}
    `;
    document.head.appendChild(style);
    const node = document.createElement('div');
    node.id = 'digiAuth';
    node.className = 'digi-auth';
    node.hidden = true;
    node.innerHTML = `<div class="digi-auth-shell"><header class="digi-auth-topbar"><div class="digi-auth-brand"><div class="digi-auth-brand-mark">${digiUsdtLogo(42)}</div><div><strong>digiRupee</strong><small>USDT → INR settlement</small></div></div><div class="digi-auth-secure"><span class="digi-auth-secure-dot"></span> Secure access</div></header><section class="digi-auth-stage"><div class="digi-auth-visual"><div class="digi-auth-copy"><div class="digi-auth-eyebrow">Private by design</div><h1>Move value.<br>Keep control.</h1><p>One secure account for selling USDT, receiving INR and tracking every settlement.</p></div><div class="digi-auth-orb">${digiUsdtLogo(60)}</div><div class="digi-auth-chip one"><b>TRC20</b> network ready</div><div class="digi-auth-chip two"><b>24×7</b> account access</div></div><section class="digi-auth-card"><div class="digi-auth-form-wrap" id="digiAuthBody"></div></section><div class="digi-auth-foot"><span>●</span> Encrypted session · No wallet private keys stored</div></section></div>`;
    document.body.appendChild(node);
  }

  function renderAuth(mode = 'login', error = '') {
    const body = $('digiAuthBody');
    if (!body) return;
    if (mode === 'challenge') {
      body.innerHTML = `<div class="digi-auth-challenge"><div class="digi-auth-form-title"><div><h2>Two-factor verification</h2><p>Enter the code from your authenticator app or use one recovery code.</p></div><div class="digi-auth-badge">Secure check</div></div><form id="digi2faForm"><div class="digi-auth-fields"><div class="digi-auth-field"><label>VERIFICATION CODE</label><div class="digi-auth-input-shell"><div class="digi-auth-icon">◆</div><input id="digi2faCode" inputmode="text" autocomplete="one-time-code" placeholder="6-digit or recovery code" required></div></div></div><div id="digiAuthError" class="error">${esc(error)}</div><button class="digi-auth-primary" type="submit">Verify and continue</button></form></div>`;
      $('digi2faForm')?.addEventListener('submit', submitTwoFactorLogin);
      return;
    }
    const register = mode === 'register';
    body.innerHTML = `<div class="digi-auth-form-title"><div><h2>${register ? 'Create your account' : 'Welcome back'}</h2><p>${register ? 'Set up secure access in less than a minute.' : 'Sign in to your digiRupee account.'}</p></div><div class="digi-auth-badge">${register ? 'New account' : 'Member access'}</div></div><form id="digiAuthForm"><div id="digiRegisterFields" ${register ? '' : 'hidden'}><div class="digi-auth-row"><div class="digi-auth-field"><label>FULL NAME</label><div class="digi-auth-input-shell"><div class="digi-auth-icon">●</div><input id="digiFullName" autocomplete="name" maxlength="80" placeholder="Your name" ${register ? 'required' : ''}></div></div><div class="digi-auth-field"><label>MOBILE</label><div class="digi-auth-input-shell"><div class="digi-auth-icon">✦</div><input id="digiMobile" inputmode="tel" autocomplete="tel" maxlength="16" placeholder="+91..." ${register ? 'required' : ''}></div></div></div></div><div class="digi-auth-fields" style="margin-top:${register ? '11px' : '0'}"><div class="digi-auth-field"><label>EMAIL ADDRESS</label><div class="digi-auth-input-shell"><div class="digi-auth-icon">✉</div><input id="digiEmail" type="email" autocomplete="email" placeholder="name@example.com" required></div></div><div class="digi-auth-field"><label>PASSWORD</label><div class="digi-auth-input-shell"><div class="digi-auth-icon">◆</div><input id="digiPassword" type="password" autocomplete="${register ? 'new-password' : 'current-password'}" minlength="8" placeholder="Enter password" required><button class="digi-auth-password-btn" id="digiPasswordToggle" type="button">SHOW</button></div></div>${register ? `<div class="digi-auth-field"><label>REFERRAL CODE <span style="color:#5f6671">(OPTIONAL)</span></label><div class="digi-auth-input-shell"><div class="digi-auth-icon">↗</div><input id="digiReferral" autocomplete="off" maxlength="30" placeholder="Enter referral code"></div></div>` : ''}</div>${register ? '' : '<div class="digi-auth-meta">Protected session on this device</div>'}<div id="digiAuthError" class="error">${esc(error)}</div><button class="digi-auth-primary" type="submit">${register ? 'Create digiRupee account' : 'Enter digiRupee'}</button>${register ? '<p class="digi-auth-terms">By creating an account you agree to the <b>Terms</b> and <b>Privacy Policy</b>.</p><button class="digi-auth-back" type="button" data-auth-mode="login">Already have an account? Sign in</button>' : '<div class="digi-auth-register-link"><span>New user?</span><button type="button" data-auth-mode="register">Register</button></div>'}</form>`;
    body.querySelectorAll('[data-auth-mode]').forEach(button => button.addEventListener('click', () => renderAuth(button.dataset.authMode)));
    $('digiPasswordToggle')?.addEventListener('click', () => {
      const input = $('digiPassword');
      if (!input) return;
      const showing = input.type === 'text';
      input.type = showing ? 'password' : 'text';
      $('digiPasswordToggle').textContent = showing ? 'SHOW' : 'HIDE';
    });
    $('digiAuthForm')?.addEventListener('submit', submitAuth);
  }

'''

path.write_text(s[:start] + block + s[end:], encoding='utf-8')
